// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
    indent = 23,
    dedent = 24,
    blankLineStart = 25,
    Comment = 1,
    Tree = 2,
    Feature = 3,
    RegExp = 4,
    AbstractFeature = 5,
    AbstractItem = 6,
    State = 7,
    Constraints = 8,
    ConstraintsItem = 9,
    Neg = 10,
    ConstraintSign = 11,
    Brackets = 12,
    OpenBracket = 13,
    CloseBracket = 14
