// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  FeatureModel = 1,
  FeatureName = 2,
  String = 3,
  FeatureList = 4,
  Feature3 = 5,
  FeatureType = 6,
  Mandatory = 7,
  Optional = 8,
  Alternative = 9,
  Or = 10
