// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "%|OVQPOOO[QPOOOOQO'#C_'#C_OaQPO'#C^QfQPOOOOQO'#C`'#C`OkQPO,58xOyQPO'#CcQOQPOOOOQO'#Ca'#CaO!UQPO'#CiO!ZQPO1G.dOOQO'#Ce'#CeO!oQPO'#ChOyQPO'#CgO!wQPO'#CgO!|QPO'#CdO#XQPO'#CkOOQO'#Cd'#CdO#pQPO,58}O$OQPO'#C_OOQO'#Cj'#CjO$jQPO,59TOOQO-E6g-E6gOOQO,59P,59PO%RQPO,59ROyQPO,59ROOQO'#Cf'#CfOyQPO,59OOOQO-E6i-E6iOOQO-E6h-E6hOOQO1G.m1G.mO%aQPO1G.mOOQO1G.j1G.jOOQO1G.d1G.dOOQO7+$X7+$XOkQPO,58xOaQPO'#C^",
  stateData: "%x~ObOS~OcPO~OdQO~OeTO~OjVO~OfXOgXOhXOiXO~Od[Ok]Oo^O~OddO~OfXOgXOhXOiXO`QijQi~OdhOo[X~OojO~OlkOmkOnkO~OlkOmkOnkO`_Xd_Xk_Xo_X~Od[Ok]Oo^O`Va~O`UXdUXeRXfUXgUXhUXiUXjUX~OddO`]af]ag]ah]ai]aj]a~OlkOmkOnkOpoO~OlkOmkOnkOpsO~Ocfghijdh~",
  goto: "#``PPahoudz}![!e!k!r!y#S#YQSPTeYfQRPTuYfQURRtuVYUZtRWSSaVcQi^QpjRqlW`V^cjRqlXl`aipZbV^cjlZ_V^cjlQZUQgZRrtQfYRnfQcVRmc",
  nodeNames: "⚠ FeatureModel AbstractItem AbstractFeature Abstract State Feature ConstraintsSection Constraints ConstraintItem ConstraintSign Brackets Neg",
  maxTerm: 32,
  skippedNodes: [0],
  repeatNodeCount: 3,
  tokenData: "9b~RgXY!jYZ!j]^!jpq!jqr!{vw#Qxy#Vyz#[!_!`#a!c!}#l#R#S#l#T#U#z#U#V#l#V#W(i#W#Y#l#Y#Z-W#Z#a#l#a#b0g#b#c#l#c#d4X#d#o#l#o#p8O#p#q9]~!oSb~XY!jYZ!j]^!jpq!j~#QOk~~#VOn~~#[Oo~~#aOp~~#dP!`!a#g~#lOm~~#qRd~!c!}#l#R#S#l#T#o#l~$PTd~!c!}#l#R#S#l#T#`#l#`#a$`#a#o#l~$eTd~!c!}#l#R#S#l#T#h#l#h#i$t#i#o#l~$yTd~!c!}#l#R#S#l#T#X#l#X#Y%Y#Y#o#l~%_Td~!c!}#l#R#S#l#T#f#l#f#g%n#g#o#l~%sTd~!c!}#l#R#S#l#T#b#l#b#c&S#c#o#l~&XSd~!c!}#l#R#S#l#T#U&e#U#o#l~&jTd~!c!}#l#R#S#l#T#h#l#h#i&y#i#o#l~'OTd~!c!}#l#R#S#l#T#]#l#]#^'_#^#o#l~'dTd~!c!}#l#R#S#l#T#j#l#j#k's#k#o#l~'xTd~!c!}#l#R#S#l#T#X#l#X#Y(X#Y#o#l~(`Rh~d~!c!}#l#R#S#l#T#o#l~(nTd~!c!}#l#R#S#l#T#c#l#c#d(}#d#o#l~)STd~!c!}#l#R#S#l#T#b#l#b#c)c#c#o#l~)hTd~!c!}#l#R#S#l#T#g#l#g#h)w#h#o#l~)|Td~!c!}#l#R#S#l#T#h#l#h#i*]#i#o#l~*bTd~!c!}#l#R#S#l#T#f#l#f#g*q#g#o#l~*vSd~!c!}#l#R#S#l#T#U+S#U#o#l~+XTd~!c!}#l#R#S#l#T#]#l#]#^+h#^#o#l~+mTd~!c!}#l#R#S#l#T#b#l#b#c+|#c#o#l~,RTd~!c!}#l#R#S#l#T#h#l#h#i,b#i#o#l~,gTd~!c!}#l#R#S#l#T#g#l#g#h,v#h#o#l~,}Rj~d~!c!}#l#R#S#l#T#o#l~-]Td~!c!}#l#R#S#l#T#X#l#X#Y-l#Y#o#l~-qSd~!c!}#l#R#S#l#T#U-}#U#o#l~.STd~!c!}#l#R#S#l#T#h#l#h#i.c#i#o#l~.hTd~!c!}#l#R#S#l#T#i#l#i#j.w#j#o#l~.|Td~!c!}#l#R#S#l#T#f#l#f#g/]#g#o#l~/bTd~!c!}#l#R#S#l#T#X#l#X#Y/q#Y#o#l~/vTd~!c!}#l#R#S#l#T#g#l#g#h0V#h#o#l~0^Rc~d~!c!}#l#R#S#l#T#o#l~0lSd~!c!}#l#R#S#l#T#U0x#U#o#l~0}Td~!c!}#l#R#S#l#T#b#l#b#c1^#c#o#l~1cTd~!c!}#l#R#S#l#T#W#l#W#X1r#X#o#l~1wSd~!c!}#l#R#S#l#T#U2T#U#o#l~2YTd~!c!}#l#R#S#l#T#h#l#h#i2i#i#o#l~2nTd~!c!}#l#R#S#l#T#c#l#c#d2}#d#o#l~3STd~!c!}#l#R#S#l#T#f#l#f#g3c#g#o#l~3hTd~!c!}#l#R#S#l#T#m#l#m#n3w#n#o#l~4ORf~d~!c!}#l#R#S#l#T#o#l~4^Vd~!c!}#l#R#S#l#T#d#l#d#e4s#e#f#l#f#g7n#g#o#l~4xTd~!c!}#l#R#S#l#T#h#l#h#i5X#i#o#l~5^Td~!c!}#l#R#S#l#T#]#l#]#^5m#^#o#l~5rTd~!c!}#l#R#S#l#T#c#l#c#d6R#d#o#l~6WTd~!c!}#l#R#S#l#T#b#l#b#c6g#c#o#l~6lSd~!c!}#l#R#S#l#T#U6x#U#o#l~6}Td~!c!}#l#R#S#l#T#`#l#`#a7^#a#o#l~7eRg~d~!c!}#l#R#S#l#T#o#l~7uRi~d~!c!}#l#R#S#l#T#o#l~8RP#T#U8U~8XP#U#V8[~8_P#g#h8b~8eP#h#i8h~8kP#f#g8n~8qP#T#U8t~8wP#V#W8z~8}P#h#i9Q~9TP#q#r9W~9]Oe~~9bOl~",
  tokenizers: [0],
  topRules: {"FeatureModel":[0,1]},
  tokenPrec: 215
})

