// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
    version: 14,
    states: "$tOVQPOOO[QPOOOOQO'#C_'#C_OaQPO'#C^QfQPOOOOQO'#C`'#C`OkQPO,58xOyQPO'#CcQOQPOOOOQO'#Ca'#CaO!OQPO'#CgO!TQPO1G.dOOQO'#Ce'#CeO!iQPO'#CdOOQO'#Ci'#CiO!qQPO,58}O!yQPO'#C_OOQO'#Ch'#ChO#eQPO,59ROOQO-E6e-E6eOOQO'#Cf'#CfOyQPO,59OOOQO-E6g-E6gOOQO-E6f-E6fO#|QPO1G.jOOQO1G.j1G.jOOQO1G.d1G.dOkQPO,58xOaQPO'#C^",
    stateData: "$e~O`OS~OaPO~ObQO~OcTO~OhVO~OdXOeXOfXOgXO~Ob[O~Ob`O~OdXOeXOfXOgXO^QihQi~OidOjdO~Ob[O^Va~O^UXbUXcRXdUXeUXfUXgUXhUX~Ob`O^ZadZaeZafZagZahZa~OidOjdO^WibWi~Oadefghbf~",
    goto: "!t^PP_fmsbx{!S!Z!_!h!nQSPTaYbQRPTlYbQURRklVYUZkRWSS^V_RieS]V_RheTe]hQZUQcZRjkQbYRgbQ_VRf_",
    nodeNames: "⚠ FeatureModel AbstractItem AbstractFeature Abstract State Feature ConstraintsSection Constraints ConstraintItem ConstraintSign",
    maxTerm: 26,
    skippedNodes: [0],
    repeatNodeCount: 3,
    tokenData: "8p~RcXY!^YZ!^]^!^pq!^!_!`!o!c!}!z#R#S!z#T#U#Y#U#V!z#V#W'w#W#Y!z#Y#Z,f#Z#a!z#a#b/u#b#c!z#c#d3g#d#o!z#o#p7^#p#q8k~!cS`~XY!^YZ!^]^!^pq!^~!rP!`!a!u~!zOj~~#PRb~!c!}!z#R#S!z#T#o!z~#_Tb~!c!}!z#R#S!z#T#`!z#`#a#n#a#o!z~#sTb~!c!}!z#R#S!z#T#h!z#h#i$S#i#o!z~$XTb~!c!}!z#R#S!z#T#X!z#X#Y$h#Y#o!z~$mTb~!c!}!z#R#S!z#T#f!z#f#g$|#g#o!z~%RTb~!c!}!z#R#S!z#T#b!z#b#c%b#c#o!z~%gSb~!c!}!z#R#S!z#T#U%s#U#o!z~%xTb~!c!}!z#R#S!z#T#h!z#h#i&X#i#o!z~&^Tb~!c!}!z#R#S!z#T#]!z#]#^&m#^#o!z~&rTb~!c!}!z#R#S!z#T#j!z#j#k'R#k#o!z~'WTb~!c!}!z#R#S!z#T#X!z#X#Y'g#Y#o!z~'nRf~b~!c!}!z#R#S!z#T#o!z~'|Tb~!c!}!z#R#S!z#T#c!z#c#d(]#d#o!z~(bTb~!c!}!z#R#S!z#T#b!z#b#c(q#c#o!z~(vTb~!c!}!z#R#S!z#T#g!z#g#h)V#h#o!z~)[Tb~!c!}!z#R#S!z#T#h!z#h#i)k#i#o!z~)pTb~!c!}!z#R#S!z#T#f!z#f#g*P#g#o!z~*USb~!c!}!z#R#S!z#T#U*b#U#o!z~*gTb~!c!}!z#R#S!z#T#]!z#]#^*v#^#o!z~*{Tb~!c!}!z#R#S!z#T#b!z#b#c+[#c#o!z~+aTb~!c!}!z#R#S!z#T#h!z#h#i+p#i#o!z~+uTb~!c!}!z#R#S!z#T#g!z#g#h,U#h#o!z~,]Rh~b~!c!}!z#R#S!z#T#o!z~,kTb~!c!}!z#R#S!z#T#X!z#X#Y,z#Y#o!z~-PSb~!c!}!z#R#S!z#T#U-]#U#o!z~-bTb~!c!}!z#R#S!z#T#h!z#h#i-q#i#o!z~-vTb~!c!}!z#R#S!z#T#i!z#i#j.V#j#o!z~.[Tb~!c!}!z#R#S!z#T#f!z#f#g.k#g#o!z~.pTb~!c!}!z#R#S!z#T#X!z#X#Y/P#Y#o!z~/UTb~!c!}!z#R#S!z#T#g!z#g#h/e#h#o!z~/lRa~b~!c!}!z#R#S!z#T#o!z~/zSb~!c!}!z#R#S!z#T#U0W#U#o!z~0]Tb~!c!}!z#R#S!z#T#b!z#b#c0l#c#o!z~0qTb~!c!}!z#R#S!z#T#W!z#W#X1Q#X#o!z~1VSb~!c!}!z#R#S!z#T#U1c#U#o!z~1hTb~!c!}!z#R#S!z#T#h!z#h#i1w#i#o!z~1|Tb~!c!}!z#R#S!z#T#c!z#c#d2]#d#o!z~2bTb~!c!}!z#R#S!z#T#f!z#f#g2q#g#o!z~2vTb~!c!}!z#R#S!z#T#m!z#m#n3V#n#o!z~3^Rd~b~!c!}!z#R#S!z#T#o!z~3lVb~!c!}!z#R#S!z#T#d!z#d#e4R#e#f!z#f#g6|#g#o!z~4WTb~!c!}!z#R#S!z#T#h!z#h#i4g#i#o!z~4lTb~!c!}!z#R#S!z#T#]!z#]#^4{#^#o!z~5QTb~!c!}!z#R#S!z#T#c!z#c#d5a#d#o!z~5fTb~!c!}!z#R#S!z#T#b!z#b#c5u#c#o!z~5zSb~!c!}!z#R#S!z#T#U6W#U#o!z~6]Tb~!c!}!z#R#S!z#T#`!z#`#a6l#a#o!z~6sRe~b~!c!}!z#R#S!z#T#o!z~7TRg~b~!c!}!z#R#S!z#T#o!z~7aP#T#U7d~7gP#U#V7j~7mP#g#h7p~7sP#h#i7v~7yP#f#g7|~8PP#T#U8S~8VP#V#W8Y~8]P#h#i8`~8cP#q#r8f~8kOc~~8pOi~",
    tokenizers: [0],
    topRules: {"FeatureModel":[0,1]},
    tokenPrec: 150
})
